name: Simple Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  Vocabulary_app_deployment:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies for srever
        run: npm install
      - name: Install dependencies for client
        run: |
          cd client && npm install
      - name: Linting UI
        run: |
          cd client && npm run lint
      - name: Testing backend
        run: npm run test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      - name: Building the UI
        run: |
          cd client && npm run build:ui
      - name: e2e tests
        uses: cypress-io/github-action@v5
        env:
          PORT: ${{ secrets.PORT }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3001
      - name: Set up Fly.io
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,', '),'#skip') }}
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy App
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,', '),'#skip') }}
        run: npm run deploy:fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message,', '),'#skip') }}
        uses: anothrNick/github-tag-action@v1
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Success notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Vocabulary App deployment successful!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Failure notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Vocabulary App deployment fauiled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
